const GEAR = [
  "Mail Sabatons",
  "Iron Greaves",
  "Steel Greaves",
  "Rawhide Boots",
  "Goathide Boots",
  "Deerskin Boots",
  "Nubuck Boots",
  "Eelskin Boots",
  "Sharkskin Boots",
  "Shagreen Boots",
  "Stealth Boots",
  "Slink Boots",
  "Straw Sandals",
  "Wool Shoes",
  "Velvet Slippers",
  "Silk Slippers",
  "Wrapped Sandals",
  "Scholar Boots",
  "Arcanist Slippers",
  "Sorcerer Boots",
  "Linen Slippers",
  "Chain Gauntlets",
  "Iron Gauntlets",
  "Plated Gauntlets",
  "Rawhide Gloves",
  "Goathide Gloves",
  "Deerskin Gloves",
  "Silk Gloves",
  "Wool Gloves",
  "Velvet Gloves",
  "Iron Hat",
  "Cone Helmet",
  "Barbute Helmet",
  "Close Helmet",
  "Visored Helm",
  "Fine Visored Helm",
  "Leather Cap",
  "Felt Cap",
  "Tricorne",
  "Wolf Pelt",
  "Vine Circlet",
  "Iron Circlet",
  "Torture Cage",
  "Tribal Mask",
  "Festival Mask",
  "Scare Mask",
  "Plate Vest",
  "Chestplate",
  "Full Plate",
  "Silk Robe",
  "Scholar's Robe",
  "Vagabond Armour",
  "Padded Vest",
  "Leather Vest",
  "Scale Vest",
  "Ringmail",
  "Chain Hauberk",
  "Kite Shield",
  "Tower Shield",
  "Buckler",
  "Focus",
  "Twig Focus",
  "Warding Focus",
  "Shortbow",
  "Long Bow",
  "Recurve Bow",
  "Composite Bow",
  "Dualstring Bow",
  "Cultist Bow",
  "Zealot Bow",
  "Warden Bow",
  "Crude Bow",
  "Crossbow",
  "Sturdy Crossbow",
  "Heavy Crossbow",
  "Titanic Crossbow",
  "Quarterstaff",
  "Journeyman Quarterstaff",
  "Gothic Quarterstaff",
  "Long Staff",
  "Imperial Staff",
  "Wood Wand",
  "Bone Wand",
  "Crystal Wand",
  "Withered Wand",
  "Sceptre",
  "Shrine Sceptre",
  "One Hand Mace",
  "War Hammer",
  "Morning Star",
  "Club",
  "Two Hand Mace",
  "Forge Maul",
  "Crumbling Maul",
  "Iron Ring",
  "Gold Ring",
  "Ruby Ring",
  "Sapphire Ring",
  "Topaz Ring",
  "Amethyst Ring",
  "Pearl Ring",
  "Prismatic Ring",
  "Unset Ring",
  "Gold Amulet",
  "Amber Amulet",
  "Jade Amulet",
  "Lapis Amulet",
  "Lunar Amulet",
  "Bloodstone Amulet",
  "Stygian Vise",
  "Leather Belt",
  "Heavy Belt",
  "Plate Belt",
  "Utility Belt",
  "Linen Belt",
  "Rawhide Belt",
  "Quiver",
  "Fire Quiver",
  "Broadhead Quiver",
  "Sacral Quiver",
];

const CURRENCY = [
  "Chaos Orb",
  "Exalted Orb",
  "Divine Orb",
  "Orb of Alchemy",
  "Orb of Transmutation",
  "Orb of Augmentation",
  "Orb of Chance",
  "Regal Orb",
  "Vaal Orb",
  "Mirror of Kalandra",
  "Scroll of Wisdom",
  "Orb of Annulment",
  "Armourer's Scrap",
  "Blacksmith's Whetstone",
  "Arcanist's Etcher",
  "Glassblower's Bauble",
  "Gemcutter's Prism",
  "Artificer's Orb",
  "Chance Shard",
  "Transmutation Shard",
  "Regal Shard",
  "Alchemy Shard",
  "Gold",
];

const FLASK_TIERS = [
  "Lesser",
  "Medium",
  "Greater",
  "Grand",
  "Giant",
  "Colossal",
  "Gargantuan",
  "Transcendent",
  "Ultimate",
];

const FLASKS = [
  ...FLASK_TIERS.flatMap((t) => [`${t} Life Flask`, `${t} Mana Flask`]),
  "Life Flask",
  "Mana Flask",
];

const CHARMS = [
  "Thawing Charm",
  "Staunching Charm",
  "Antidote Charm",
  "Dousing Charm",
  "Grounding Charm",
  "Stone Charm",
  "Silver Charm",
  "Ruby Charm",
  "Sapphire Charm",
  "Topaz Charm",
  "Amethyst Charm",
  "Golden Charm",
  "Cleansing Charm",
];

const OTHER = [
  "Uncut Skill Gem",
  "Uncut Support Gem",
  "Uncut Spirit Gem",
  ...FLASKS,
  ...CHARMS,
  "Ruby",
  "Emerald",
  "Sapphire",
  "Time-Lost Ruby",
  "Time-Lost Emerald",
  "Time-Lost Sapphire",
];

const WAYSTONES = Array.from({ length: 16 }, (_, i) => `Waystone (Tier ${i + 1})`);

const TIERS = ["", "Advanced ", "Expert ", "Exceptional "];

export const BASE_TYPES: string[] = [
  ...new Set([
    ...GEAR.flatMap((b) => TIERS.map((t) => `${t}${b}`)),
    ...CURRENCY,
    ...OTHER,
    ...WAYSTONES,
  ]),
].sort((a, b) => b.length - a.length);

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

export function matchBaseType(name: string): string | null {
  const n = name.trim();
  if (!n) return null;
  for (const base of BASE_TYPES) {
    if (n === base) return base;
    const re = new RegExp(`(?:^|\\s)${escapeRegExp(base)}(?:\\s|$)`, "i");
    if (re.test(n)) return base;
  }
  return null;
}
