import type { DropItem, LootFilter } from "./types";
import { newId } from "./catalog";

export const PIT_FARMER: LootFilter = {
  id: "preset-pit",
  name: "Pit Farmer",
  scatterSeed: 7741,
  rules: [
    {
      id: newId("r"),
      name: "GA Legendaries",
      enabled: true,
      visibility: "recolor",
      color: "#f08a2a",
      conditions: [
        { kind: "requiredAffixes", affixes: ["max_life", "armor", "cdr"], atLeast: 1 },
        { kind: "greaterAffix", atLeast: 1, compare: "atLeast" },
        { kind: "codex", enabled: true },
        { kind: "properties", ancestral: true, mythic: false },
        { kind: "rarity", rarities: ["legendary"] },
        { kind: "itemPower", min: 800, max: 1000 },
      ],
    },
    {
      id: newId("r"),
      name: "GA Uniques",
      enabled: true,
      visibility: "recolor",
      color: "#e8c45a",
      conditions: [
        { kind: "greaterAffix", atLeast: 1, compare: "atLeast" },
        { kind: "rarity", rarities: ["unique"] },
      ],
    },
    {
      id: newId("r"),
      name: "GA Weapons",
      enabled: true,
      visibility: "recolor",
      color: "#e05656",
      conditions: [
        {
          kind: "itemType",
          types: [
            "axe",
            "axe2h",
            "mace",
            "mace2h",
            "sword",
            "sword2h",
            "dagger",
            "polearm",
            "staff",
            "wand",
            "bow",
            "crossbow",
            "scythe",
            "scythe2h",
            "quarterstaff",
            "glaive",
          ],
          allClasses: false,
        },
        { kind: "greaterAffix", atLeast: 1, compare: "atLeast" },
      ],
    },
    {
      id: newId("r"),
      name: "Mythic Uniques",
      enabled: true,
      visibility: "recolor",
      color: "#f0d090",
      conditions: [
        { kind: "properties", ancestral: false, mythic: true },
        { kind: "rarity", rarities: ["unique", "mythic"] },
      ],
    },
    {
      id: newId("r"),
      name: "Talismans",
      enabled: true,
      visibility: "recolor",
      color: "#6fd08a",
      conditions: [{ kind: "itemType", types: ["charm", "seal"], allClasses: false }],
    },
    {
      id: newId("r"),
      name: "Codex Upgrade",
      enabled: true,
      visibility: "recolor",
      color: "#6fd08a",
      conditions: [{ kind: "codex", enabled: true }],
    },
    {
      id: newId("r"),
      name: "Non-GA junk",
      enabled: true,
      visibility: "hideAll",
      color: "#888888",
      conditions: [
        { kind: "rarity", rarities: ["common", "magic", "rare", "legendary"] },
        { kind: "greaterAffix", atLeast: 1, compare: "fewerThan" },
      ],
    },
  ],
};

export const STARTER_FILTER: LootFilter = {
  id: "preset-starter",
  name: "New Filter",
  scatterSeed: 1901,
  rules: [],
};

export const DEMO_DROPS: DropItem[] = [
  {
    id: "d1",
    name: "Heir of Perdition",
    base: "Helm",
    slot: "helm",
    rarity: "mythic",
    itemPower: 950,
    ancestral: true,
    mythic: true,
    greaterAffixes: 1,
    affixes: ["crit_chance", "lucky_hit"],
    uniqueName: "Heir of Perdition",
  },
  {
    id: "d2",
    name: "Ancestral Runic Breastplate",
    base: "Chest",
    slot: "chest",
    rarity: "legendary",
    itemPower: 925,
    ancestral: true,
    mythic: false,
    greaterAffixes: 2,
    affixes: ["max_life", "armor", "all_res"],
    codexUpgrade: true,
  },
  {
    id: "d3",
    name: "Tibault's Will",
    base: "Pants",
    slot: "pants",
    rarity: "unique",
    itemPower: 910,
    ancestral: true,
    mythic: false,
    greaterAffixes: 1,
    affixes: ["max_life", "damage"],
    uniqueName: "Tibault's Will",
  },
  {
    id: "d4",
    name: "Sacred Battle Axe",
    base: "Axe",
    slot: "axe",
    rarity: "legendary",
    itemPower: 880,
    ancestral: true,
    mythic: false,
    greaterAffixes: 1,
    affixes: ["crit_damage", "vulnerable"],
    codexUpgrade: false,
  },
  {
    id: "d5",
    name: "Rare Leather Gloves",
    base: "Gloves",
    slot: "gloves",
    rarity: "rare",
    itemPower: 760,
    ancestral: false,
    mythic: false,
    greaterAffixes: 0,
    affixes: ["attack_speed", "crit_chance"],
  },
  {
    id: "d6",
    name: "Magic Wand of the Magus",
    base: "Wand",
    slot: "wand",
    rarity: "magic",
    itemPower: 640,
    ancestral: false,
    mythic: false,
    greaterAffixes: 0,
    affixes: ["intelligence"],
  },
  {
    id: "d7",
    name: "Nilfur Charm",
    base: "Charm",
    slot: "charm",
    rarity: "legendary",
    itemPower: 800,
    ancestral: true,
    mythic: false,
    greaterAffixes: 0,
    affixes: ["ranks"],
    talismanSet: "nilfur",
  },
  {
    id: "d8",
    name: "Ring of Starless Skies",
    base: "Ring",
    slot: "ring",
    rarity: "mythic",
    itemPower: 940,
    ancestral: true,
    mythic: true,
    greaterAffixes: 0,
    affixes: ["crit_chance", "lucky_hit", "resource_cost"],
    uniqueName: "Ring of Starless Skies",
  },
  {
    id: "d9",
    name: "Legendary Boneweave Boots",
    base: "Boots",
    slot: "boots",
    rarity: "legendary",
    itemPower: 820,
    ancestral: false,
    mythic: false,
    greaterAffixes: 0,
    affixes: ["move_speed", "max_life"],
    codexUpgrade: true,
  },
  {
    id: "d10",
    name: "Common Iron Sword",
    base: "Sword",
    slot: "sword",
    rarity: "common",
    itemPower: 200,
    ancestral: false,
    mythic: false,
    greaterAffixes: 0,
    affixes: [],
  },
];
